version: '3.5'
services:
  api1: # API - Instância 01
    # image: api
    build: .
    hostname: api1
    restart: always
    depends_on:
      - db
      - cache
    expose:
      - "80"
    environment:
      DATABASE_URL: postgres://rinha:tw1tt3r@db:5432/rinha
      CACHE_URL: cache:6379
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  api2: # API - Instância 01
    # image: api
    build: .
    hostname: api2
    restart: always
    depends_on:
      - db
      - cache
    expose:
      - "80"
    environment:
      DATABASE_URL: postgres://rinha:tw1tt3r@db:5432/rinha
      CACHE_URL: cache:6379
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  nginx: # Load Balancer
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  db: # Banco de dados
    image: postgres
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '1.0GB'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: tw1tt3r
      POSTGRES_USER: rinha
    volumes:
      - ./db/seed.sql:/docker-entrypoint-initdb.d/init.sql
  
  cache:
    hostname: cache
    image: redis:latest
    ports:
      - '6379:6379'
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'