name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - name: Build
        run: go build -v cmd/main.go
  test:
    runs-on: ubuntu-20.04
    needs: build
    steps:
    - uses: actions/checkout@v3
    - run: docker-compose up -d
    - run: |
        git clone --single-branch https://github.com/zanfranceschi/rinha-de-backend-2023-q3
        cd rinha-de-backend-2023-q3
        wget https://repo1.maven.org/maven2/io/gatling/highcharts/gatling-charts-highcharts-bundle/3.9.5/gatling-charts-highcharts-bundle-3.9.5-bundle.zip
        unzip gatling-charts-highcharts-bundle-3.9.5-bundle.zip
        cd gatling-charts-highcharts-bundle-3.9.5
        ./bin/gatling.sh -rm local -s RinhaBackendSimulation -rd "DESCRICAO" -rf $WORKSPACE/user-files/results -sf $WORKSPACE/user-files/simulations -rsf $WORKSPACE/user-files/resources
      env:
        WORKSPACE: ${{ github.workspace }}/rinha-de-backend-2023-q3/stress-test
        
    
